#!/bin/bash

PWD=`pwd`
WIKIDIR=../selinux.wiki

if [ \! -d $WIKIDIR ]; then
    git clone git@github.com:SELinuxProject/selinux.wiki.git $WIKIDIR
fi

if [ -z "$RELEASE_TAG"]; then
    RELEASE_TAG=$(date '+%Y%m%d')
fi
DEST=releases/$RELEASE_TAG
DIRS="libsepol libselinux libsemanage checkpolicy secilc policycoreutils mcstrans restorecond semodule-utils"
DIRS_NEED_PREFIX="dbus gui python sandbox"

git tag -a $RELEASE_TAG -m "Release $RELEASE_TAG"

rm -rf $DEST
mkdir -p $DEST

for i in $DIRS; do
	cd $i
	VERS=`cat VERSION`
	ARCHIVE=$i-$VERS.tar.gz
	git tag $i-$VERS > /dev/null 2>&1
	git archive --format=tar --prefix=$i-$VERS/ $i-$VERS | gzip > ../$DEST/$ARCHIVE
	cd ..
done

for i in $DIRS_NEED_PREFIX; do
	cd $i
	VERS=`cat VERSION`
	ARCHIVE=selinux-$i-$VERS.tar.gz
	git tag selinux-$i-$VERS > /dev/null 2>&1
	git archive --format=tar --prefix=selinux-$i-$VERS/ selinux-$i-$VERS | gzip > ../$DEST/$ARCHIVE
	cd ..
done

git shortlog 20190315..$RELEASE_TAG > $DEST/shortlog-$RELEASE_TAG.txt
git log 20190315..$RELEASE_TAG > $DEST/log-$RELEASE_TAG.txt

cat > $DEST/RELEASE-$RELEASE_TAG.txt <<EOF
RELEASE $RELEASE_TAG (3.0-rc1)

User-visible changes:

* Optional support for kernel policy optimization (enable with
optimize-policy=true in /etc/selinux/semanage.conf for modular policy or -O
option to checkpolicy/secilc for monolithic policy); this is optional because it
provides relatively small savings with non-trivial policy compile-time overhead
for some policies e.g. Android.

* New digest scheme for setfiles/restorecon -D; instead of a single hash of the
entire file contexts configuration stored in a security.restorecon_last xattr on
only the top-level directory, use a hash of all partial matches from file
contexts stored in a security.sehash xattr on each directory,

* Support for default_range glblub in source policy (.te/policy.conf and CIL)
and kernel policy version 32,

* New libselinux APIs for querying validatetrans rules,

* Unknown permissions are now handled as errors in CIL,

* security_av_string() no longer returns immediately upon encountering an
unknown permission and will log all known permissions,

* checkmodule -c support for specifying module policy version,

* mcstransd reverted to original color range matching based on dominance

Issues fixed:
EOF

cd $DEST

git add .

echo "Add the following to the $WIKIDIR/Releases.md wiki page:"

echo ""

echo "## Release $(date '+%Y-%m-%d')"

echo ""

echo "[Release Notes](https://github.com/SELinuxProject/selinux/releases/download/$RELEASE_TAG/RELEASE-$RELEASE_TAG.txt)"
echo ""
echo "[full log](https://github.com/SELinuxProject/selinux/releases/download/$RELEASE_TAG/log-$RELEASE_TAG.txt)"
echo ""
echo "[short log](https://github.com/SELinuxProject/selinux/releases/download/$RELEASE_TAG/shortlog-$RELEASE_TAG.txt)"
echo ""

for i in *.tar.gz; do

	echo -n "[$i](https://github.com/SELinuxProject/selinux/releases/download/$RELEASE_TAG/$i) "
	sha256sum $i | cut -d " " -f 1
	echo ""
done

echo "And then run:"
echo "  cd $WIKIDIR"
echo "  git commit  -m \"Release $RELEASE_TAG\" -a -s"
echo "  git push"

echo ""
echo "Push the release and its tags to git via:"
echo "  git push"
echo "  git push --tags"

echo ""
echo "Create a new release from the latest tag on https://github.com/SELinuxProject/selinux/tags"

echo ""
echo "Add files from releases/$RELEASE_TAG as assets to the new github release"
